language: java
sudo: enabled

addons:
  sh_known_hosts: 93.4.202.148
  apt:
    packages:
    - sshpass

jdk:
- oraclejdk8
script:
- mvn compile
- mvn package
- mvn test

before_deploy:
 - chmod ugo+x scripts/deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: sudo sshpass -p '$SSH_PASS' scp -P $SSH_PORT target/AtlantisJEE.war $SSH_USER@$SSH_ENDPOINT:$DEPLOY_PATH
    on:
      branch: master

