language: java


addons:

  ssh_known_hosts:
  - 93.4.202.148
  apt:
    packages:
    - sshpass

jdk:
- oraclejdk8
script:
- mvn compile
- mvn package
- mvn test

before_deploy:
 - chmod +x scripts/deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master

